# Generated by Django 4.0.3 on 2022-04-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.CharField(max_length=60)),
                ('nomeProfessor', models.CharField(max_length=30)),
                ('idProfessor', models.IntegerField()),
            ],
        ),
    ]
